### ISSUE TITLE
Reporting of nutrition facts should follow federal labeling standards

### ISSUE THREAD

**Issue by ericfoster** [YaleMenus/ios#53]
Federal standards govern how nutrition facts look on all labels. I'm not worried about people going to jail; it's more that it looks weird when there are 0.03 grams of fat. These are the rules for how to round:

<img width="819" alt="Screen Shot 2021-01-27 at 22 39 41" src="https://user-images.githubusercontent.com/2925815/106100116-a6b17f80-60f0-11eb-99e6-44efede728af.png">
<img width="828" alt="Screen Shot 2021-01-27 at 22 39 54" src="https://user-images.githubusercontent.com/2925815/106100122-aa450680-60f0-11eb-822a-b8fc4e539eb3.png">

See more on pp129-130 here: https://www.fda.gov/files/food/published/Food-Labeling-Guide-%28PDF%29.pdf

Even if you do not want to hard code the exact rules in, you might want to at least convert the values to ints

![Simulator Screen Shot - iPhone 11 - 2021-01-27 at 22 24 30](https://user-images.githubusercontent.com/2925815/106100160-bc26a980-60f0-11eb-838f-88299ac40278.png)

**Comment by ErikBoesen** [comment]
Fixed on server-side.
